# Generated by Django 4.2.5 on 2023-09-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='system', max_length=150),
        ),
    ]
