# Generated by Django 4.2.5 on 2023-09-18 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_user_task_user_id_task_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='username',
        ),
    ]
